---
- hosts: workstation

  tasks:
    - name: install Alfred
      mac_pkg: pkg_type=app state=present
               url=http://cachefly.alfredapp.com/Alfred_2.0.8_212.zip
               dest=alfred2.zip archive_type=zip archive_path='Alfred 2.app'
      sudo: yes

