---
- hosts: workstation

  tasks:
    - name: install java 7 update 51
      mac_pkg: pkg_name=com.oracle.jdk7u51 pkg_version=1.1
               url=http://download.oracle.com/otn-pub/java/jdk/7u51-b13/jdk-7u51-macosx-x64.dmg
               curl_opts="-L --cookie oraclelicense=accept-securebackup-cookie"
               archive_type=dmg archive_path='JDK 7 Update 51.pkg'
      sudo: yes

