---
- hosts: workstation

  tasks:
    - name: install java 7 update 25
      mac_pkg: pkg_name=com.oracle.jdk7u51 pkg_version=1.1
               url=http://download.oracle.com/otn-pub/java/jdk/7u51-b13/jdk-7u51-macosx-x64.dmg
               curl_opts='--cookie gpw_e24=http%3A%2F%2Fwww.oracle.com'
               archive_type=dmg archive_path='JDK 7 Update 25.pkg'
      sudo: yes

