---
- hosts: workstation

  tasks:
    - name: install spectacle
      mac_pkg: pkg_type=app
               url=https://s3.amazonaws.com/spectacle/downloads/Spectacle+0.8.8.zip
               archive_type=zip archive_path='Spectacle.app'
      sudo: yes

